#!/bin/bash

sh format-partitions.sh
sh source.sh

mkdir -pv $LFS/tools && ln -sv $LFS/tools /

# export MAKEFLAGS='-j 2'

cd $LFS/sources
tar -jxf binutils-2.25.1.tar.bz2 && cd binutils-2.25.1
export LFS_TGT=`./config.guess`
cd $LFS/sources

sh build-binutils.sh
sh build-gcc.sh
sh build-api-headers.sh
sh build-glibc.sh
sh build-libstdc++.sh

sh build-binutils-pass2.sh
sh build-gcc-pass2.sh
sh build-tcl-core.sh
sh build-expect.sh
sh build-deja-gnu.sh
sh build-check.sh
sh build-ncurses.sh
sh build-bash.sh
sh build-bzip2.sh
sh build-coreutils.sh
sh build-diffutils.sh
sh build-file.sh
sh build-findutils.sh
sh build-gawk.sh
sh build-gettext.sh
sh build-grep.sh
sh build-gzip.sh
sh build-m4.sh
sh build-make.sh
sh build-patch.sh
sh build-perl.sh
sh build-sed.sh
sh build-tar.sh
sh build-texinfo.sh
sh build-util-linux.sh
sh build-xz.sh
sh build-stripping.sh
